### ISSUE TITLE
Run Outside ASP

### ISSUE THREAD

**Issue by mjavad007** [hermanho/postal.aspnetcore#12]
In old postal, you could use it that outside ASP as shown here 
[http://aboutcode.net/postal/outside-aspnet.html](url).
Could be used with Hangfire ([https://docs.hangfire.io/en/latest/tutorials/send-email.html](url)) to send email in background. 
Also the previous one supported strong classes via model.
Can you help me how to do it via your library if possible.

**Comment by hermanho** [comment]
It cannot be running without ASP.Net Core since it is leverage the RazorViewEngine from Microsoft.AspNetCore.App.
Strong classes is still supported.

**Comment by matishadow** [comment]
I did manage to accomplish it. 

I've used `Razor.Templating.Core` package to render the views.
Using it I created my implementation of `ITemplateService`:

```csharp
    public class TestTemplateService : ITemplateService
    {
        public Task<string> RenderTemplateAsync<TViewModel>(RouteData routeData, string viewName, TViewModel viewModel,
            Dictionary<string, object> additionalViewDictionary = null, bool isMainPage = true)
            where TViewModel : IViewData
        {
            viewModel.ViewData.ToList().ForEach(x => additionalViewDictionary?.Add(x.Key, x.Value));

            var htmlString = RazorTemplateEngine
                .RenderAsync($"/Views/Emails/{viewName}.cshtml", viewModel,
                    additionalViewDictionary ?? new Dictionary<string, object>());

            return htmlString;
        }
    }
```

Then I injected it:
`serviceCollection.AddTransient<ITemplateService, TestTemplateService>();`
after calling `services.AddPostal();`
