### ISSUE TITLE
Empty Line in header breaks Email

### ISSUE THREAD

**Issue by DaleCam** [hermanho/postal.aspnetcore#18]
Just either a note for future users of this - or a potential future fix (although it might be hard to distinguish a fix for plain text messages), if there is an empty line in your headers  like below (between from and cc lines) it breaks the email and sends it as plain text with the cc as the first line of the email. It took me a while to figure this out as I am programatically constructing the header in a partial razor file based on the Model, and also because this wasnt an issue in the previous version of postal.

subject: =?UTF-8?B?TWFwIDcgQ2hlY2tlZCBPdXQ=?=
content-transfer-encoding: base64
content-type: text/html; charset=utf-8
to: =?UTF-8?B?RGFsZBDY1lcmu?= <to@example.com>
from: =?UTF-8?B?QmVuamFgTGF1cmVudA==?= via <mailroom@example.org>

cc: someone-else@example.com

**Comment by DaleCam** [comment]
Potential solution might be to continue parsing lines, until you get a non blank line that cannot be interpreted as a header line...

**Comment by hermanho** [comment]
This behavior (line break between headers and contents) should be long long time ago. How come it was working in previous version?

**Comment by DaleCam** [comment]
Hi Man, I appreciate your work. I have no idea why it was working in the previous version! Unless its something to do with the new ViewEngine of asp.net core?

**Comment by hermanho** [comment]
> Hi Man, I appreciate your work. I have no idea why it was working in the previous version! Unless its something to do with the new ViewEngine of asp.net core?

Could you please share version number which was working?
