### ISSUE TITLE
'Postal.Email' does not contain a definition for 'Send'

### ISSUE THREAD

**Issue by yangar** [hermanho/postal.aspnetcore#4]
I ve got the following error with .net core 2.1:
`RuntimeBinderException: 'Postal.Email' does not contain a definition for 'Send'`
```
 dynamic email = new Email("MyTemplate");
 email.From = Email;
 email.Description = Description;
 email.FirstName = FirstName;
 email.LastName = LastName;
 email.UserId = UserId;
 email.IP = Request.HttpContext.Connection.RemoteIpAddress.ToString();
 email.Send();
```

Does it work with .net core 2.1 ?

**Comment by hermanho** [comment]
Please replace by "SendAsync"

https://github.com/hermanho/postal.aspnetcore/blob/fcb9957ea9041f2242f5362e07a9063507fc8bc9/src/Postal.AspNetCore/Email.cs#L96

**Comment by kyleherzog** [comment]
I'm not finding an example of using SendAsync.  How do you go about creating the IEmailService?

**Comment by hermanho** [comment]
https://github.com/hermanho/postal.aspnetcore.samples/blob/a5eeb22f50fe99d582835f5194d3db764dda0dd7/WebSample/Controllers/HomeController.cs#L73

IEmailService is created by dependency injection.
You can check example source https://github.com/hermanho/postal.aspnetcore.samples
