### ISSUE TITLE
Please support OdeToCode FeatureFolders

### ISSUE THREAD

**Issue by TDK1964** [hermanho/postal.aspnetcore#7]
I'm using the about but have a problem in that the template (Testing1.cshtml) cannot be found.

**Comment by hermanho** [comment]
Please provide a repo to reproduce the problem.

**Comment by Lumono** [comment]
![Postal Mailer](https://user-images.githubusercontent.com/13352317/54310441-9ab98480-458f-11e9-87a3-8623e41c29b7.jpg)
when I move Testing1.cshtml to another folder, the Testing1.cshtml can't be found.
How I can use the view that is in any subfolder.
e.g. I have project, make folder from project root, Views/Inspection/Document/
I put Testing1.cshtml to Document folder, the Testing1.cshtml can't be found.

**Comment by Lumono** [comment]
or I want to use following View (RegistrationAreas.cshtml) from DocumentController
![Postal Mailer1](https://user-images.githubusercontent.com/13352317/54314448-ed4b6e80-4598-11e9-86f0-2bb6d558249c.jpg)

**Comment by hermanho** [comment]
@Lumono It has a limitation to search the template under the folder "Emails" currently but I think it can be enhanced to support all templates under the views folder.
Would you mind to create a new issue?
